--- # compponents and their config locations
- name: "i3-gaps"
  action: replace
  config_loc: ~/.config/i3/config
  ref_loc: i3_config

- name: "Xmodmap"
  action: replace
  config_loc: ~/.Xmodmap
  skip_for_vm: true
  ref_loc: Xmodmap

- name: "Xresources"
  action: append
  config_loc: ~/.Xresources
  ref_loc: Xresources

- name: "fish-alias"
  action: replace
  config_loc: ~/.config/fish/alias_abbr.fish
  ref_loc: fish_alias_abbr.fish

- name: "fish-config"
  action: append
  config_loc: ~/.config/fish/config.fish
  ref_loc: fish_config.fish

- name: "gtk3-settings"
  action: append
  config_loc: ~/.config/gtk-3.0/settings.ini
  ref_loc: gtk_settings.ini

- name: "gtk4-settings"
  action: append
  config_loc: ~/.config/gtk-4.0/settings.ini
  ref_loc: gtk_settings.ini

- name: "gtk5-settings"
  action: append
  config_loc: ~/.config/gtk-5.0/settings.ini
  ref_loc: gtk_settings.ini

- name: "polybar"
  action: replace
  config_loc: ~/.config/polybar/config
  ref_loc: polybar_config

- name: "polybar-launcher"
  action: replace
  config_loc: ~/.config/polybar/polybar_launcher.sh
  ref_loc: polybar_launcher.sh

- name: "rofi"
  action: replace
  config_loc: ~/.config/rofi/config.rasi
  ref_loc: rofi_config.rasi

- name: "vscode-keybindings"
  action: replace
  config_loc: ~/.config/Code/User/keybindings.json
  ref_loc: vscode_keybindings.json

- name: "vscode-settings"
  action: replace
  config_loc: ~/.config/Code/User/settings.json
  ref_loc: vscode_settings.json

- name: "bashrc"
  action: append
  config_loc: ~/.bash_profile
  ref_loc: bash_profile

- name: "vimrc"
  action: replace
  config_loc: ~/.vimrc
  ref_loc: vimrc

- name: "tmux"
  action: replace
  config_loc: ~/.tmux.conf
  ref_loc: tmux.conf

- name: "wallpaper-image"
  action: replace
  config_loc: ~/.config/wallpapers/004.png
  ref_loc: 004.png

- name: "i3exit"
  action: replace
  config_loc: ~/.config/i3/i3exit
  ref_loc: i3exit.sh

- name: "fish_emacs_conf"
  action: replace
  config_loc: ~/.config/fish/conf.d/emacs.fish
  ref_loc: fish_emacs.fish

- name: "compton_setup"
  actino: replace
  config_loc: ~/.config/i3/compton.conf
  ref_loc: compton.conf
