export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

# some more ls aliases
alias ll='ls -lF'
alias la='ls -A'
alias l='ls -CF'

# setting fish shell as default without chsh
fish_shell=$(which fish)
export SHELL="${fish_shell}"
exec "${fish_shell}" -l